# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='hostels',
            field=models.ManyToManyField(blank=True, to='hostels.Hostel'),
        ),
    ]
