# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_auto_20160517_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='actual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.Order'),
        ),
    ]
