# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_auto_20160517_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Забронирован'), (2, 'Ожидает подтверждения брони'), (3, 'Бронирование отменено'), (4, 'Активен'), (5, 'Готов к завершению'), (6, 'Успешно завершён')], verbose_name='Статус'),
        ),
    ]
