# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_auto_20160519_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostels.Bed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='actual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_bed', to='hostels.Order', verbose_name='Текущий заказ'),
        ),
    ]
