# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_auto_20160519_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='actual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_bed', to='hostels.Order', verbose_name='Текущий заказ'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Заселение'), (1, 'Изменение сроков проживания')], verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.Bed', verbose_name='Кровать'),
        ),
    ]
